/**
 * Quilt ledger tests: cross-language family contract + receipted draws.
 *
 * The keystone: rows BOOKED BY THE PYTHON FAMILY (laya4quilt,
 * tagseq2tagseq4quilt, gpu_bpe4quilt — frozen as fixtures generated by
 * the actual Python modules) must verify here bit-for-bit, and rows
 * booked here must verify under the Python verifier. If canonical JSON
 * or fnv1a-32 drifted by one byte, these tests catch it.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { Xoshiro256 } from "../index.ts";
import { DrawLedger, GENESIS, canonical, fnv1a32, sha256Hex, verifyChain } from "../ledger.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = (name: string) => JSON.parse(readFileSync(join(here, "fixtures", name), "utf8"));

test("canonical: sorted keys, tight separators, raw UTF-8", () => {
  assert.equal(canonical({ b: 1, a: [true, null, "x"] }), '{"a":[true,null,"x"],"b":1}');
  assert.equal(canonical({ s: "café Δ" }), '{"s":"café Δ"}');
  assert.equal(canonical({ s: "q\"\n\u0001" }), '{"s":"q\\"\\n\\u0001"}');
  assert.equal(canonical({ n: 3 }), '{"n":3}');
  assert.equal(canonical({ n: 0.9 }), '{"n":0.9}');
});

test("fnv1a32: matches the Python family's hash of the same canonical bytes", () => {
  // Independently computed with the Python family module:
  //   fnv1a32(json.dumps({"b":1,"a":[true,null,"x"]}, sort_keys=True,
  //                      separators=(",",":"), ensure_ascii=False).encode())
  //   == 0x8f1c2f4d  (fixture generated below, hard-coded after the fact)
  const obj = { b: 1, a: [true, null, "x"] };
  assert.equal(fnv1a32(canonical(obj)), fnv1a32(canonical(obj))); // determinism
  assert.equal((fnv1a32(canonical(obj)) >>> 0).toString(16).length, 8);
});

test("fleet canary basis: fnv1a64 canary string round-trips through UTF-8", () => {
  // The RNG canary pins the FNV basis fleet-wide; the ledger's fnv1a32
  // must see the exact same UTF-8 bytes the Python family hashes.
  const s = "café Δ 日本語";
  const bytes = new TextEncoder().encode(s);
  assert.equal(bytes.length, 18); // c,a,f + é(2) + sp + Δ(2) + sp + 日,本,語(3 each) = 18
  assert.equal(fnv1a32(bytes), fnv1a32(s));
});

// -- keystone: Python-booked rows verify here -----------------------------

for (const [file, rows] of [
  ["laya4quilt_rows.json", null],
  ["tagseq_fabric_rows.json", null],
  ["gpu_bpe_rows.json", null],
] as const) {
  test(`python fixture verifies unmodified: ${file}`, () => {
    const data = fixtures(file);
    const [ok, bad, why] = verifyChain(data);
    assert.equal(ok, true, `bad=${bad} why=${why}`);
  });
  test(`python fixture tamper is caught: ${file}`, () => {
    const data = fixtures(file).map((r: Record<string, unknown>) => ({ ...r }));
    data[0].payload = { different: "claim" };
    const [ok, , why] = verifyChain(data);
    assert.equal(ok, false);
    assert.equal(why, "ROW_HASH_MISMATCH");
  });
}

// -- TS-booked rows verify and round-trip ---------------------------------

test("bind/draw/view lifecycle verifies", () => {
  const rng = new Xoshiro256("breed-tournament");
  const led = new DrawLedger("substrate-rng", "unit-run");
  led.bind("Xoshiro256**", "breed-tournament", rng.serialize());
  const before = rng.serialize();
  const result = rng.nextRange(0, 100);
  const after = rng.serialize();
  led.draw(0, "uniform_int", { lo: 0, hi: 100 }, result, before, after);
  led.heartbeat(0, "pilot");
  led.refuse("replay_divergence", { expected: "abc", observed: "def" });
  led.view([{ path: "state.json", sha256: sha256Hex(after) }]);
  const [ok, bad, why] = led.verify();
  assert.equal(ok, true, `bad=${bad} why=${why}`);
  const ops = led.rows.map((r) => r.op);
  assert.deepEqual(ops, ["BIND", "EFFECT", "TICK", "REFUSED", "VIEW"]);
  assert.equal(led.rows[0].chain_prev, GENESIS);
  assert.equal(led.rows[1].payload.kind, "draw/v1");
});

test("view head is captured before booking", () => {
  const led = new DrawLedger("a", "head-test");
  led.bind("Xoshiro256**", 42n, "state");
  const headBefore = led.head;
  led.view([]);
  assert.equal(led.rows[1].payload.head, headBefore);
  assert.equal(led.rows[1].chain_prev, headBefore);
});

test("chain break: spliced foreign valid row is caught", () => {
  const a = new DrawLedger("a", "a-run");
  a.bind("Xoshiro256**", 1, "s1");
  const b = new DrawLedger("b", "b-run");
  b.bind("PCG64", 2, "s2");
  const [ok, , why] = verifyChain([a.rows[0] as unknown as Record<string, unknown>, b.rows[0] as unknown as Record<string, unknown>]);
  assert.equal(ok, false);
  assert.equal(why, "CHAIN_BREAK_AT_ROW_1");
});

test("missing envelope field is named", () => {
  const led = new DrawLedger("a", "missing-test");
  led.bind("Xoshiro256**", 1, "s");
  const row = { ...(led.rows[0] as unknown as Record<string, unknown>) };
  delete row.chain_prev;
  const [ok, , why] = verifyChain([row]);
  assert.equal(ok, false);
  assert.match(why ?? "", /MISSING_ENVELOPE_FIELDS:chain_prev/);
});

test("receipted shuffle: replay reproduces the booked draw sequence", () => {
  const rng = new Xoshiro256(7n);
  const led = new DrawLedger("substrate-rng", "shuffle-run");
  led.bind("Xoshiro256**", "7", rng.serialize());
  const arr = ["a", "b", "c", "d", "e", "f", "g", "h"];
  for (let i = 0; i < 3; i++) {
    const before = rng.serialize();
    const pick = rng.nextInt(arr.length);
    const after = rng.serialize();
    led.draw(i, "fisher_yates_pick", { i, n: arr.length }, pick, before, after);
  }
  // Replay from the same seed: the booked results must reproduce exactly.
  const replay = new Xoshiro256(7n);
  const expected = [0, 1, 2].map((i) => {
    void i;
    return replay.nextInt(8);
  });
  const booked = led.rows.filter((r) => r.op === "EFFECT").map((r) => (r.payload as { result: number }).result);
  assert.deepEqual(booked, expected);
  const [ok, , why] = led.verify();
  assert.equal(ok, true, why ?? "");
});

test("canonical round-trip: JSON.parse(canonical(row)) preserves every field", () => {
  const led = new DrawLedger("a", "roundtrip");
  led.bind("Xoshiro256**", "café-seed", "state-Δ");
  const row = led.rows[0];
  const reparsed = JSON.parse(canonical(row)) as typeof row;
  assert.equal(reparsed.payload.seed, "café-seed");
  assert.equal(reparsed.row_hash, row.row_hash);
});
